language:
    - objective-c

env:
    - BUILD_TYPE=Debug TOOLCHAIN=analyze
    - BUILD_TYPE=Release TOOLCHAIN=analyze

before_install:
    - brew update

install:
    - brew install cmake

    # download toolchains
    - wget https://github.com/ruslo/polly/archive/v0.2.1.tar.gz
    - tar xf v0.2.1.tar.gz
    - export POLLY_ROOT=`pwd`/polly-0.2.1
    # -- end

script:
    - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/${TOOLCHAIN}.cmake
    - cmake --build _builds --config ${BUILD_TYPE}
    - ctest -VV -C ${BUILD_TYPE}
